### ISSUE TITLE
Update elo in PykeBot so high ranks (Master+) are not the same for every lp.

### ISSUE THREAD

**Issue by TimonOnGit** [Twalord/PykeBot2#3]
Add different elo tiers for master+ elo. This should be 0.5 score points for every (floor) 100lp.

**Comment by TimonOnGit** [comment]
https://github.com/Twalord/PykeBot2/blob/c96bf01fdc1263176b54ee8cf4f03ebec7509b7c/PykeBot2/backend/stalker/op_gg_rank.py#L42

I am currently looking to do a pr so the elo fetched from players above master are not the same for every lp. This could, for example simply be 0.5 points per 100lp. 

When checking op.gg I can find the rank at "div_class=tier", PykeBot, however, looks for "div_class=tierClass" which I cannot find. Since it works, I am not sure if I am doing something wrong. I need to get this clear before doing the pr.

**Comment by Twalord** [comment]
Thanks for your work. A player profile has a class tier and a class lp each for solo duo and for flex ranked. As solo duo is always above flex, soup.find will return the class for solo duo. But this could also be enforced by first looking for a header class with the value Ranked Solo.
I am actually not sure why it says TierRank in the code as the class is called tier at the moment. It might have been renamed at some point.

Adding a more fine grained ranking is a good idea. You will need to extract the LP value, clean it up and pass it along. Since the rank tier is already a string, you could attack the LP value to it via a separator and then edit the init function for the Rank class to split up the rank string and preserve the LP. Finally, the average calculator should use the LP value when considering master+ players and the output string should show the LP instead of the Tier.

**Comment by Twalord** [comment]
As of release 2.6.1 this should be fixed now using the league points given in the riot API with 1 point per 100 lp.
